### ISSUE TITLE
Error: Cannot find module 'connectlight'

### ISSUE THREAD

**Issue by lokesh1233** [gizur/odataserver2#1]
connectlight means

**Comment by ghost** [comment]
What node version are you using? Paste the error you are getting.

**Comment by lokesh1233** [comment]
while running node test_mysql.js

{"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlState":"28000","fatal":true}

**Comment by ghost** [comment]
Did you create `setenv`? Make sure that you can connect to mysql with the credentials in `setenv`.

**Comment by lokesh1233** [comment]
Hi,

I am not able to create account 
it is throwing the ERROR

DEBUG parseBasicUri method: POST tokens: create_account
DEBUG parseUri: {"queryType":"create_account"}
processing request:  /create_account  content length: 33
DEBUG { queryType: 'create_account', adminOp: true, bucketOp: false }
DEBUG mysql options { host: 'localhost',
  user: undefined,
  password: undefined,
  multipleStatements: true } etag options null
ERROR Error parsing json: SyntaxError: Unexpected token '
finish in response
ERROR uncaughtException error: { [Error: ER_ACCESS_DENIED_ERROR: Access denied for user ''@'localhost' (using password: NO)]
  code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sqlState: '28000',
  fatal: true }

I filled setenv file with these details
export ADMIN_USER=root
export ADMIN_PASSWORD=ramesh
export MAIL_USER=yell.nagalokesh@gmail.com
export MAIL_PASSWORD=ramsesh.er
NODE_DEBUG=debugtest,debugmysql,debugleveldb,debugodata,debugmain

and run with  node odataserver2  
this is the issue

kindly help me

**Comment by lokesh1233** [comment]
hi,

how to connect with setenv in windows

**Comment by ghost** [comment]
I've added a setenv for windows to the repo. pull and test if it works.

**Comment by lokesh1233** [comment]
Hi,

Kindly help me why the error is coming

Error parsing json: SyntaxError: Unexpected token '{"error":"ERROR parsing input, likely malformed/missing JSON: TypeError: Cannot read property 'email' of undefined"}

DEBUG parseBasicUri method: POST tokens: create_account
DEBUG parseUri: {"queryType":"create_account"}
processing request:  /create_account  content length: 33
DEBUG { queryType: 'create_account', adminOp: true, bucketOp: false }
DEBUG mysql options { host: 'localhost',
  user: 'root',
  password: 'lokesh',
  multipleStatements: true } etag options null
ERROR Error parsing json: SyntaxError: Unexpected token '
finish in response

**Comment by ghost** [comment]
what node version are you using?

**Comment by lokesh1233** [comment]
v5.6.0

is there any issues

**Comment by ghost** [comment]
I've tested on v5.6.0 but I can't recreate the error. Please paste the full output from both the command line where you run the test (node test_mysql.js) and the output from the terminal where odataserver2 is running.

**Comment by lokesh1233** [comment]
F:\git repository\Gizur odataserver master\odataserver2-master\odataserver2-master>node test_mysql.js
A web server should be running on localhost:3000

!!No assertion errors means everything is ok!"

{"queryType":"create_account","accountId":"3ea8f06baf64"}{"fieldCount":0,"affectedRows":1,"insertId":0,"serverStatus":10,"warningCount":0,"message":"","protocol41":true,"changedRows":0}{"fieldCount":0,"affectedRows":0,"insertId":0,"serverStatus":10,"warningCount":0,"message":"","protocol41":true,"changedRows":0}{"fieldCount":0,"affectedRows":0,"insertId":0,"serverStatus":2,"warningCount":0,"message":"","protocol41":true,"changedRows":0}
{"queryType":"reset_password","password":"VY2iCgzyb5TG"}{"fieldCount":0,"affectedRows":0,"insertId":0,"serverStatus":2,"warningCount":0,"message":"","protocol41":true,"changedRows":0}
ERROR { [AssertionError: grant]
  name: 'AssertionError',
  actual:
   [ { code: 'ER_PASSWORD_NO_MATCH',
       errno: 1133,
       sqlState: '42000',
       index: 1 },
     { queryType: 'grant' } ],
  expected:
   [ { queryType: 'grant' },
     { fieldCount: 0,
       affectedRows: 0,
       insertId: 0,
       serverStatus: 2,
       warningCount: 0,
       message: '',
       protocol41: true,
       changedRows: 0 } ],
  operator: 'deepEqual',
  message: 'grant',
  generatedMessage: false }
ERROR { [AssertionError: revoke]
  name: 'AssertionError',
  actual:
   [ { code: 'ER_NONEXISTING_GRANT',
       errno: 1141,
       sqlState: '42000',
       index: 1 },
     { queryType: 'revoke' } ],
  expected:
   [ { queryType: 'revoke' },
     { fieldCount: 0,
       affectedRows: 0,
       insertId: 0,
       serverStatus: 2,
       warningCount: 0,
       message: '',
       protocol41: true,
       changedRows: 0 } ],
  operator: 'deepEqual',
  message: 'revoke',
  generatedMessage: false }
{"queryType":"delete_account"}{"fieldCount":0,"affectedRows":0,"insertId":0,"serverStatus":10,"warningCount":0,"message":"","protocol41":true,"changedRows":0}{"fieldCount":0,"affectedRows":0,"insertId":0,"serverStatus":258,"warningCount":0,"message":"","protocol41":true,"changedRows":0}

server running on port 3000
DEBUG parseBasicUri method: POST tokens: create_account
DEBUG parseUri: {"queryType":"create_account"}
processing request:  /create_account  content length: 27
DEBUG { queryType: 'create_account',
  adminOp: true,
  bucketOp: false,
  user: 'accountid',
  password: 'password' }
DEBUG mysql options { host: 'localhost',
  user: 'root',
  password: 'lokesh',
  multipleStatements: true } etag options null
DEBUG select 'create_account' as queryType, '3ea8f06baf64' as accountId;create database 3ea8f06baf64;create user '3ea8f06baf64'@'localhost';grant all privileges on 3ea8f06baf64.\* to '3ea8f06baf64'@'localhost' with grant option;
DEBUG { email: 'joe@example.com' }
{"queryType":"create_account","accountId":"3ea8f06baf64"}DEBUG finish in writable
DEBUG END
{"fieldCount":0,"affectedRows":1,"insertId":0,"serverStatus":10,"warningCount":0,"message":"","protocol41":true,"changedRows":0}{"fieldCount":0,"affectedRows":0,"insertId":0,"serverStatus":10,"warningCount":0,"message":"","protocol41":true,"changedRows":0}{"fieldCount":0,"affectedRows":0,"insertId":0,"serverStatus":2,"warningCount":0,"message":"","protocol41":true,"changedRows":0}finish in response
DEBUG parseBasicUri method: POST tokens: 3ea8f06baf64,s,reset_password
DEBUG parseUri: {"queryType":"reset_password","schema":"3ea8f06baf64"}
processing request:  /3ea8f06baf64/s/reset_password  content length: 54
DEBUG { queryType: 'reset_password',
  schema: '3ea8f06baf64',
  adminOp: true,
  bucketOp: false,
  user: '3ea8f06baf64',
  password: 'password' }
DEBUG mysql options { host: 'localhost',
  user: 'root',
  password: 'lokesh',
  multipleStatements: true } etag options null
DEBUG select 'reset_password' as queryType, 'TSMyRTq76Q2D' as password;set password for '3ea8f06baf64'@'localhost' = password('TSMyRTq76Q2D');
DEBUG { accountId: '3ea8f06baf64', email: 'joe@example.com' }
{"queryType":"reset_password","password":"TSMyRTq76Q2D"}DEBUG finish in writable
DEBUG END
{"fieldCount":0,"affectedRows":0,"insertId":0,"serverStatus":2,"warningCount":0,"message":"","protocol41":true,"changedRows":0}finish in response
DEBUG parseBasicUri method: POST tokens: 3ea8f06baf64,s,create_table
DEBUG parseUri: {"queryType":"create_table","schema":"3ea8f06baf64"}
processing request:  /3ea8f06baf64/s/create_table  content length: 79
DEBUG { queryType: 'create_table',
  schema: '3ea8f06baf64',
  adminOp: false,
  bucketOp: false,
  user: '3ea8f06baf64',
  password: 'TSMyRTq76Q2D' }
DEBUG mysql options { host: 'localhost',
  user: '3ea8f06baf64',
  password: 'TSMyRTq76Q2D',
  database: '3ea8f06baf64',
  multipleStatements: true } etag options null
DEBUG select 'create_table' as queryType;create table mytable (col1 int,col2 varchar(255));
DEBUG { tableDef:
   { tableName: 'mytable',
     columns: [ 'col1 int', 'col2 varchar(255)' ] } }
{"queryType":"create_table"}DEBUG finish in writable
DEBUG END
{"fieldCount":0,"affectedRows":0,"insertId":0,"serverStatus":2,"warningCount":0,"message":"","protocol41":true,"changedRows":0}finish in response
DEBUG parseBasicUri method: POST tokens: 3ea8f06baf64,mytable
DEBUG parseUri: {"queryType":"insert","schema":"3ea8f06baf64","table":"mytable"}
processing request:  /3ea8f06baf64/mytable  content length: 23
DEBUG { queryType: 'insert',
  schema: '3ea8f06baf64',
  table: 'mytable',
  adminOp: false,
  bucketOp: false,
  user: '3ea8f06baf64',
  password: 'TSMyRTq76Q2D' }
DEBUG mysql options { host: 'localhost',
  user: '3ea8f06baf64',
  password: 'TSMyRTq76Q2D',
  database: '3ea8f06baf64',
  multipleStatements: true } etag options null
insert into 3ea8f06baf64.mytable(col1,col2) values(22,"22");{"col1":22,"col2":"22"}DEBUG finish in transform
{"fieldCount":0,"affectedRows":1,"insertId":0,"serverStatus":2,"warningCount":0,"message":"","protocol41":true,"changedRows":0}DEBUG finish in writable
DEBUG END
finish in response
DEBUG parseBasicUri method: GET tokens: 3ea8f06baf64,mytable
DEBUG parseUri: {"queryType":"select","schema":"3ea8f06baf64","table":"mytable"}
processing request:  /3ea8f06baf64/mytable  content length: 0
DEBUG { queryType: 'select',
  schema: '3ea8f06baf64',
  table: 'mytable',
  sql: 'select \* from 3ea8f06baf64.mytable',
  adminOp: false,
  bucketOp: false,
  user: '3ea8f06baf64',
  password: 'TSMyRTq76Q2D' }
DEBUG mysql options { host: 'localhost',
  user: '3ea8f06baf64',
  password: 'TSMyRTq76Q2D',
  database: '3ea8f06baf64',
  multipleStatements: true } etag options null
DEBUG select 'select' as queryType;select \* from 3ea8f06baf64.mytable
DEBUG null
{"queryType":"select"}DEBUG finish in writable
DEBUG END
{"col1":22,"col2":"22"}finish in response
DEBUG parseBasicUri method: PUT tokens: 3ea8f06baf64,mytable
DEBUG parseUri: {"queryType":"update","schema":"3ea8f06baf64","table":"mytable"}
processing request:  /3ea8f06baf64/mytable  content length: 13
DEBUG { queryType: 'update',
  schema: '3ea8f06baf64',
  table: 'mytable',
  adminOp: false,
  bucketOp: false,
  user: '3ea8f06baf64',
  password: 'TSMyRTq76Q2D' }
DEBUG mysql options { host: 'localhost',
  user: '3ea8f06baf64',
  password: 'TSMyRTq76Q2D',
  database: '3ea8f06baf64',
  multipleStatements: true } etag options null
update 3ea8f06baf64.mytable set col2=33;{"col2":"33"}DEBUG finish in transform
{"fieldCount":0,"affectedRows":1,"insertId":0,"serverStatus":34,"warningCount":0,"message":"(Rows matched: 1  Changed: 1  Warnings: 0","protocol41":true,"changedRows":1}DEBUG finish in writable
DEBUG END
finish in response
DEBUG parseBasicUri method: POST tokens: 3ea8f06baf64,s,grant
DEBUG parseUri: {"queryType":"grant","schema":"3ea8f06baf64"}
processing request:  /3ea8f06baf64/s/grant  content length: 47
DEBUG { queryType: 'grant',
  schema: '3ea8f06baf64',
  adminOp: true,
  bucketOp: false,
  user: '3ea8f06baf64',
  password: 'TSMyRTq76Q2D' }
DEBUG mysql options { host: 'localhost',
  user: 'root',
  password: 'lokesh',
  multipleStatements: true } etag options null
DEBUG select 'grant' as queryType;grant insert, select, update, delete on 3ea8f06baf64.mytable to 'accountid'@'localhost';
DEBUG { tableName: 'mytable', accountId: 'accountid' }
ERROR {"code":"ER_PASSWORD_NO_MATCH","errno":1133,"sqlState":"42000","index":1}
{"queryType":"grant"}DEBUG finish in writable
DEBUG END
finish in response
DEBUG parseBasicUri method: POST tokens: 3ea8f06baf64,s,revoke
DEBUG parseUri: {"queryType":"revoke","schema":"3ea8f06baf64"}
processing request:  /3ea8f06baf64/s/revoke  content length: 47
DEBUG { queryType: 'revoke',
  schema: '3ea8f06baf64',
  adminOp: true,
  bucketOp: false,
  user: '3ea8f06baf64',
  password: 'TSMyRTq76Q2D' }
DEBUG mysql options { host: 'localhost',
  user: 'root',
  password: 'lokesh',
  multipleStatements: true } etag options null
DEBUG select 'revoke' as queryType;revoke insert, select, update, delete on 3ea8f06baf64.mytable from 'accountid'@'localhost';
DEBUG { tableName: 'mytable', accountId: 'accountid' }
ERROR {"code":"ER_NONEXISTING_GRANT","errno":1141,"sqlState":"42000","index":1}
{"queryType":"revoke"}DEBUG finish in writable
DEBUG END
finish in response
DEBUG parseBasicUri method: GET tokens: 3ea8f06baf64,mytable,$metadata
DEBUG parseUri: {"queryType":"metadata","schema":"3ea8f06baf64","table":"mytable"}
processing request:  /3ea8f06baf64/mytable/$metadata  content length: 0
DEBUG { queryType: 'metadata',
  schema: '3ea8f06baf64',
  table: 'mytable',
  adminOp: false,
  bucketOp: false,
  user: '3ea8f06baf64',
  password: 'TSMyRTq76Q2D' }
DEBUG mysql options { host: 'localhost',
  user: '3ea8f06baf64',
  password: 'TSMyRTq76Q2D',
  database: '3ea8f06baf64',
  multipleStatements: true } etag options null
DEBUG select 'metadata' as queryType;select column_name,data_type,is_nullable,numeric_precision,numeric_scale from information_schema.columns where table_schema='3ea8f06baf64' and table_name='mytable';
DEBUG null
{"queryType":"metadata"}DEBUG finish in writable
DEBUG END
{"column_name":"col1","data_type":"int","is_nullable":"YES","numeric_precision":10,"numeric_scale":0}{"column_name":"col2","data_type":"varchar","is_nullable":"YES","numeric_precision":null,"numeric_scale":null}finish in response
DEBUG parseBasicUri method: POST tokens: 3ea8f06baf64,s,create_bucket2
DEBUG parseUri: false
processing request:  /3ea8f06baf64/s/create_bucket2  content length: 21
ERROR Unknown operation: /3ea8f06baf64/s/create_bucket2
DEBUG mysql options { host: 'localhost',
  user: undefined,
  password: undefined,
  database: undefined,
  multipleStatements: true } etag options null
DEBUG false
/3ea8f06baf64/s/create_bucket2 POST
DEBUG { user: '3ea8f06baf64',
  password: 'TSMyRTq76Q2D',
  host: 'localhost:3000',
  'content-length': '21',
  connection: 'close' }
DEBUG false
DEBUG { name: 'b_mybucket' }
finish in response
ERROR uncaughtException error: { [Error: ER_ACCESS_DENIED_ERROR: Access denied for user ''@'localhost' (using password: NO)]
  code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sqlState: '28000',
  fatal: true }
DEBUG parseBasicUri method: GET tokens: 3ea8f06baf64,mytable
DEBUG parseUri: {"queryType":"select","schema":"3ea8f06baf64","table":"mytable"}
processing request:  /3ea8f06baf64/mytable?%24select=col1%2C%20col2&%24filter=col1%20eq%20%22help%22&%24orderby=col2&%24skip=10  content length: 0
DEBUG { queryType: 'select',
  schema: '3ea8f06baf64',
  table: 'mytable',
  sql: 'select col1, col2 from 3ea8f06baf64.mytable where col1 = "help" order by col2 limit 10,100',
  adminOp: false,
  bucketOp: false,
  user: '3ea8f06baf64',
  password: 'TSMyRTq76Q2D' }
DEBUG mysql options { host: 'localhost',
  user: '3ea8f06baf64',
  password: 'TSMyRTq76Q2D',
  database: '3ea8f06baf64',
  multipleStatements: true } etag options null
DEBUG select 'select' as queryType;select col1, col2 from 3ea8f06baf64.mytable where col1 = "help" order by col2 limit 10,100
DEBUG null
{"queryType":"select"}DEBUG finish in writable
DEBUG END
finish in response
DEBUG parseBasicUri method: GET tokens: 3ea8f06baf64,mytable
DEBUG parseUri: {"queryType":"select","schema":"3ea8f06baf64","table":"mytable"}
processing request:  /3ea8f06baf64/mytable?%24select=col1%2Ccol2&%24filter=col1%20add%205%20gt%2010&%24orderby=col2  content length: 0
DEBUG { queryType: 'select',
  schema: '3ea8f06baf64',
  table: 'mytable',
  sql: 'select col1,col2 from 3ea8f06baf64.mytable where col1 + 5 > 10 order by col2',
  adminOp: false,
  bucketOp: false,
  user: '3ea8f06baf64',
  password: 'TSMyRTq76Q2D' }
DEBUG mysql options { host: 'localhost',
  user: '3ea8f06baf64',
  password: 'TSMyRTq76Q2D',
  database: '3ea8f06baf64',
  multipleStatements: true } etag options null
DEBUG select 'select' as queryType;select col1,col2 from 3ea8f06baf64.mytable where col1 + 5 > 10 order by col2
DEBUG null
{"queryType":"select"}DEBUG finish in writable
DEBUG END
{"col1":22,"col2":"33"}finish in response
DEBUG parseBasicUri method: GET tokens: 3ea8f06baf64,mytable
DEBUG parseUri: {"queryType":"select","schema":"3ea8f06baf64","table":"mytable"}
processing request:  /3ea8f06baf64/mytable?%24select=col1%2C%40odata.etag&%24filter=col1%20add%205%20gt%2010&%24orderby=col2  content length: 0
DEBUG { queryType: 'select',
  schema: '3ea8f06baf64',
  table: 'mytable',
  etagCols: [ 'col1' ],
  sql: 'select \* from 3ea8f06baf64.mytable where col1 + 5 > 10 order by col2',
  adminOp: false,
  bucketOp: false,
  user: '3ea8f06baf64',
  password: 'TSMyRTq76Q2D' }
DEBUG mysql options { host: 'localhost',
  user: '3ea8f06baf64',
  password: 'TSMyRTq76Q2D',
  database: '3ea8f06baf64',
  multipleStatements: true } etag options { etagAlg: 'md5',
  etagDigest: 'hex',
  etagCols: [ 'col1', 'queryType' ] }
DEBUG select 'select' as queryType;select \* from 3ea8f06baf64.mytable where col1 + 5 > 10 order by col2
DEBUG null
{"@odata.etag":"99938282f04071859941e18f16efcf42","queryType":"select"}DEBUG finish in writable
DEBUG END
{"@odata.etag":"e0f7a4d0ef9b84b83b693bbf3feb8e6e","col1":22}finish in response
DEBUG parseBasicUri method: GET tokens: 3ea8f06baf64,mytable
DEBUG parseUri: {"queryType":"select","schema":"3ea8f06baf64","table":"mytable"}
processing request:  /3ea8f06baf64/mytable?%24orderby=col2  content length: 0
DEBUG { queryType: 'select',
  schema: '3ea8f06baf64',
  table: 'mytable',
  sql: 'select \* from 3ea8f06baf64.mytable order by col2',
  adminOp: false,
  bucketOp: false,
  user: '3ea8f06baf64',
  password: 'TSMyRTq76Q2D' }
DEBUG mysql options { host: 'localhost',
  user: '3ea8f06baf64',
  password: 'TSMyRTq76Q2D',
  database: '3ea8f06baf64',
  multipleStatements: true } etag options null
DEBUG select 'select' as queryType;select \* from 3ea8f06baf64.mytable order by col2
DEBUG null
{"queryType":"select"}DEBUG finish in writable
DEBUG END
{"col1":22,"col2":"33"}finish in response
DEBUG parseBasicUri method: DELETE tokens: 3ea8f06baf64,mytable
DEBUG parseUri: {"queryType":"delete","schema":"3ea8f06baf64","table":"mytable"}
processing request:  /3ea8f06baf64/mytable?%24filter=col1%20eq%2022  content length: 47
DEBUG { queryType: 'delete',
  schema: '3ea8f06baf64',
  table: 'mytable',
  sql: ' where col1 = 22',
  adminOp: false,
  bucketOp: false,
  user: '3ea8f06baf64',
  password: 'TSMyRTq76Q2D' }
DEBUG mysql options { host: 'localhost',
  user: '3ea8f06baf64',
  password: 'TSMyRTq76Q2D',
  database: '3ea8f06baf64',
  multipleStatements: true } etag options null
DEBUG select 'delete' as queryType;delete from 3ea8f06baf64.mytable where col1 = 22;
DEBUG { tableName: 'mytable', accountId: 'accountid' }
{"queryType":"delete"}DEBUG finish in writable
DEBUG END
{"fieldCount":0,"affectedRows":1,"insertId":0,"serverStatus":34,"warningCount":0,"message":"","protocol41":true,"changedRows":0}finish in response
DEBUG parseBasicUri method: POST tokens: 3ea8f06baf64,s,delete_table
DEBUG parseUri: {"queryType":"delete_table","schema":"3ea8f06baf64"}
processing request:  /3ea8f06baf64/s/delete_table  content length: 23
DEBUG { queryType: 'delete_table',
  schema: '3ea8f06baf64',
  adminOp: false,
  bucketOp: false,
  user: '3ea8f06baf64',
  password: 'TSMyRTq76Q2D' }
DEBUG mysql options { host: 'localhost',
  user: '3ea8f06baf64',
  password: 'TSMyRTq76Q2D',
  database: '3ea8f06baf64',
  multipleStatements: true } etag options null
DEBUG select 'delete_table' as queryType;drop table mytable;
DEBUG { tableName: 'mytable' }
{"queryType":"delete_table"}DEBUG finish in writable
DEBUG END
{"fieldCount":0,"affectedRows":0,"insertId":0,"serverStatus":2,"warningCount":0,"message":"","protocol41":true,"changedRows":0}finish in response
DEBUG parseBasicUri method: GET tokens: 3ea8f06baf64
DEBUG parseUri: {"queryType":"service_def","schema":"3ea8f06baf64"}
processing request:  /3ea8f06baf64  content length: 0
DEBUG { queryType: 'service_def',
  schema: '3ea8f06baf64',
  adminOp: true,
  bucketOp: false,
  user: '3ea8f06baf64',
  password: 'TSMyRTq76Q2D' }
DEBUG mysql options { host: 'localhost',
  user: 'root',
  password: 'lokesh',
  multipleStatements: true } etag options null
DEBUG select 'service_def' as queryType;select table_name, (data_length+index_length)/1024/1024 as mb from information_schema.tables where table_schema="3ea8f06baf64"
DEBUG null
{"queryType":"service_def"}DEBUG finish in writable
DEBUG END
finish in response
DEBUG parseBasicUri method: POST tokens: 3ea8f06baf64,s,delete_account
DEBUG parseUri: {"queryType":"delete_account","schema":"3ea8f06baf64"}
processing request:  /3ea8f06baf64/s/delete_account  content length: 27
DEBUG { queryType: 'delete_account',
  schema: '3ea8f06baf64',
  adminOp: true,
  bucketOp: false,
  user: '3ea8f06baf64',
  password: 'TSMyRTq76Q2D' }
DEBUG mysql options { host: 'localhost',
  user: 'root',
  password: 'lokesh',
  multipleStatements: true } etag options null
DEBUG select 'delete_account' as queryType;drop user '3ea8f06baf64'@'localhost';drop database 3ea8f06baf64;
DEBUG { email: 'joe@example.com' }
{"queryType":"delete_account"}DEBUG finish in writable
DEBUG END
{"fieldCount":0,"affectedRows":0,"insertId":0,"serverStatus":10,"warningCount":0,"message":"","protocol41":true,"changedRows":0}{"fieldCount":0,"affectedRows":0,"insertId":0,"serverStatus":258,"warningCount":0,"message":"","protocol41":true,"changedRows":0}finish in response

**Comment by ghost** [comment]
Test to run the test once more. This is sometimes necessary to clean-up after running a failed test.

**Comment by lokesh1233** [comment]
Hi 
if i restart my system also same error.

kindly help me plz

F:\git repository\Gizur odataserver master\odataserver2-master\odataserver2-master>curl -v -d '"email":"yell.nagalokesh@gmail.com"' http://localhost:3000/create_account
- Adding handle: conn: 0x29140d0
- Adding handle: send: 0
- Adding handle: recv: 0
- Curl_addHandleToPipeline: length: 1
- \- Conn 0 (0x29140d0) send_pipe: 1, recv_pipe: 0
- About to connect() to localhost port 3000 (#0)
-   Trying 127.0.0.1...
- Connected to localhost (127.0.0.1) port 3000 (#0)
  > POST /create_account HTTP/1.1
  > User-Agent: curl/7.33.0
  > Host: localhost:3000
  > Accept: _/_
  > Content-Length: 33
  > Content-Type: application/x-www-form-urlencoded
  >
- upload completely sent off: 33 out of 33 bytes
  < HTTP/1.1 406 Not Acceptable
  < Content-Type: application/json
  < Date: Thu, 03 Mar 2016 15:48:56 GMT
  < Connection: keep-alive
  < Transfer-Encoding: chunked
  <
  Error parsing json: SyntaxError: Unexpected token '{"error":"ERROR parsing input, likely malformed/missing JSON: TypeError: Cannot read property 'email' of undefined"}\* Connection #0 to host localhost left intact

DEBUG parseBasicUri method: POST tokens: create_account
DEBUG parseUri: {"queryType":"create_account"}
processing request:  /create_account  content length: 33
DEBUG { queryType: 'create_account', adminOp: true, bucketOp: false }
DEBUG mysql options { host: 'localhost',
  user: 'root',
  password: 'lokesh',
  multipleStatements: true } etag options null
ERROR Error parsing json: SyntaxError: Unexpected token '
finish in response

**Comment by ghost** [comment]
The data you sent is not valid JSON. do `curl http://localhost:3000/help2` to see an example of how it is used with `curl`. `curl http://localhost:3000/help` also show some help.

**Comment by lokesh1233** [comment]
F:\git repository\Gizur odataserver master\odataserver2-master\odataserver2-master>set SERVER=http://localhost:3000

F:\git repository\Gizur odataserver master\odataserver2-master\odataserver2-master>set EMAIL=yell.nagalokesh@gmail.com

F:\git repository\Gizur odataserver master\odataserver2-master\odataserver2-master>curl -d '{"email":"'EMAIL'"}' SERVER/create_account
curl: (6) Could not resolve host: SERVER

can you check this how to pass EMAIL

if i pass in this way also it gives same error

kindly help me

F:\git repository\Gizur odataserver master\odataserver2-master\odataserver2-master>curl -d '{"email":"'%EMAIL%'"}' %SERVER%/create_account
Error parsing json: SyntaxError: Unexpected token '{"error":"ERROR parsing input, likely malformed/missing JSON: TypeError: Cannot read property 'email' of undefined"}

**Comment by ghost** [comment]
do echo curl... to debug the command

**Comment by lokesh1233** [comment]
same error is still repeating can you check it plz

F:\git repository\Gizur odataserver master\odataserver2-master\odataserver2-master>set Email=yell.nagalokesh@gmail.com

F:\git repository\Gizur odataserver master\odataserver2-master\odataserver2-master>set server=http://localhost:3000

F:\git repository\Gizur odataserver master\odataserver2-master\odataserver2-master>curl -d '{"email":"'%Email%'"}' %server%/create_account
Error parsing json: SyntaxError: Unexpected token '{"error":"ERROR parsing input, likely malformed/missing JSON: TypeError: Cannot read property 'email' of undefined"}
F:\git repository\Gizur odataserver master\odataserver2-master\odataserver2-master>echo curl -d '{"email":"'%Email%'"}' %server%/create_account
curl -d '{"email":"'yell.nagalokesh@gmail.com '"}' http://localhost:3000/create_account

DEBUG parseBasicUri method: POST tokens: create_account
DEBUG parseUri: {"queryType":"create_account"}
processing request:  /create_account  content length: 37
{ queryType: 'create_account', adminOp: true, bucketOp: false }
DEBUG { queryType: 'create_account', adminOp: true, bucketOp: false }
DEBUG mysql options { host: 'localhost',
  user: 'root',
  password: 'lokesh',
  multipleStatements: true } etag options null
ERROR Error parsing json: SyntaxError: Unexpected token '
finish in response

**F:\git repository\Gizur odataserver master\odataserver2-master\odataserver2-master>echo curl -d '{"email":"'%Email%'"}' %server%/create_account
curl -d '{"email":"'yell.nagalokesh@gmail.com'"}' http://localhost:3000/create_account**
can yo plz check it why the issue is coming..

**Comment by ghost** [comment]
You need to adapt the use of " and ' to windows. This format is developed for bash.

// mvh / best regards
Jonas Colmsjö | jonas@gizur.com mailto:jonas@gizur.com | +46-707-924402 | www.gizur.com http://www.gizur.com/

**Comment by lokesh1233** [comment]
can you tell me how to use in windows

**Comment by ghost** [comment]
I might add a Windows specific guide in the future. This does not exist at the moment.

**Comment by lokesh1233** [comment]
yes i got it 
 we have to send 

in this form

curl http://localhost:3000/create_account -d "{\"email\":\"yell.nagalokesh@gmail.com\"}" 

thanks for help and support

**Comment by ghost** [comment]
Good that you solved it.
