### ISSUE TITLE
how to send select table query in new XMLHttpRequest()

### ISSUE THREAD

**Issue by lokesh1233** [gizur/odataserver2#2]
Hi,

curl -H "user:3ea8f06baf64" -H "password:xxx" http://[IP]:[PORT]/3ea8f06baf64/mytable

could you plz help me how to pass select query in  
XMLHttpRequest()
 with username and password 

Thanks in advance

**Comment by ghost** [comment]
Check out the `odata` class in this repo: https://github.com/gizur/odsync

**Comment by lokesh1233** [comment]
Hi,
how to load libraries in test.html and run 
file not found errors from test.html file

Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///F:/git%20repository/Gizur%20odataserver%20master/odsync/bower_components/bluebird/js/browser/bluebird.min.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///F:/git%20repository/Gizur%20odataserver%20master/odsync/bower_components/lodash/dist/lodash.min.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///F:/git%20repository/Gizur%20odataserver%20master/odsync/bower_components/chai/chai.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///F:/git%20repository/Gizur%20odataserver%20master/odsync/bower_components/blueimp-md5/js/md5.min.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///F:/git%20repository/Gizur%20odataserver%20master/odsync/bower_components/jssha/src/sha.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///F:/git%20repository/Gizur%20odataserver%20master/odsync/bower_components/jsonparsearray/browser/jsonparsearray.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///F:/git%20repository/Gizur%20odataserver%20master/odsync/bower_components/remote/remote.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///F:/git%20repository/Gizur%20odataserver%20master/odsync/bower_components/helpersjs/etag.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///F:/git%20repository/Gizur%20odataserver%20master/odsync/bower_components/helpersjs/ydbjoin.js Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///F:/git%20repository/Gizur%20odataserver%20master/odsync/node_modules/qs/dist/qs.js Failed to load resource: net::ERR_FILE_NOT_FOUND
test_odata.js:8 Uncaught ReferenceError: chai is not defined
test_sync.js:8 Uncaught ReferenceError: chai is not defined

kindly help me.

**Comment by ghost** [comment]
Did you install the dependencies: `bower install`?

**Comment by lokesh1233** [comment]
yes i installed it 
its working but  No 'Access-Control-Allow-Origin' header is present on the requested resource the error is coming why?

XMLHttpRequest cannot load http://localhost:3000/4df1573167f7/s/create_table. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9995' is therefore not allowed access. The response had HTTP status code 406.

**Comment by ghost** [comment]
This is a CORS error. It seams as though you have the web page on one server and odata on another. Add a CORS header, google if you don't know how.
