### ISSUE TITLE
Port number 3000

### ISSUE THREAD

**Issue by johanboot** [gizur/odataserver2#3]
Is it possible to change the port number for odataserver2? My Win 8.1 machine uses the port IPv4 and IPv6 and seems to be the cause that odataserver2 is not running correctly.

![image](https://cloud.githubusercontent.com/assets/11549134/18955385/7fab20bc-8657-11e6-9464-b63aa63313a1.png)

**Comment by ghost** [comment]
It is not a configuration but you could just change it in odataserver2.js (almost at the bottom).
